-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.21 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2015-08-15 11:35:05
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping structure for table intita.course
DROP TABLE IF EXISTS `course`;
CREATE TABLE IF NOT EXISTS `course` (
  `course_ID` int(11) NOT NULL AUTO_INCREMENT,
  `alias` varchar(20) NOT NULL,
  `language` varchar(6) NOT NULL,
  `title_ua` varchar(100) NOT NULL,
  `title_ru` varchar(100) DEFAULT NULL,
  `title_en` varchar(100) DEFAULT NULL,
  `level` enum('intern','junior','strong junior','middle','senior') NOT NULL,
  `start` date DEFAULT NULL,
  `status` tinyint(4) NOT NULL,
  `modules_count` int(255) DEFAULT NULL,
  `course_duration_hours` int(11) NOT NULL,
  `course_price` decimal(10,0) DEFAULT NULL,
  `for_whom_ua` text,
  `what_you_learn_ua` text,
  `what_you_get_ua` text,
  `for_whom_ru` text,
  `what_you_learn_ru` text,
  `what_you_get_ru` text,
  `for_whom_en` text,
  `what_you_learn_en` text,
  `what_you_get_en` text,
  `course_img` varchar(255) DEFAULT 'courseimg1.png',
  `rating` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`course_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='status: 0 - in develop, 1 - avaliable';

-- Dumping data for table intita.course: ~14 rows (approximately)
/*!40000 ALTER TABLE `course` DISABLE KEYS */;
INSERT INTO `course` (`course_ID`, `alias`, `language`, `title_ua`, `title_ru`, `title_en`, `level`, `start`, `status`, `modules_count`, `course_duration_hours`, `course_price`, `for_whom_ua`, `what_you_learn_ua`, `what_you_get_ua`, `for_whom_ru`, `what_you_learn_ru`, `what_you_get_ru`, `for_whom_en`, `what_you_learn_en`, `what_you_get_en`, `course_img`, `rating`) VALUES
	(1, 'coursePhp', 'ua', 'Інтернет програміст (РНР)', 'Интернет программист (РНР)', 'Web developer (PHP)', 'strong junior', '2015-07-30', 0, 21, 89, 6548, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', 'кто отвечает за постановку задач на разработку;', 'Вы научитесь писать чистый код', 'Видеозаписи и текстовые материалы всех онлайн-занятий', 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', 'What you learn description', 'What you get description', 'course1Image.png', 9),
	(2, 'courseJavaScript', 'ua', 'Інтернет програміст (Java Script)', 'Интернет программист  (Java Script)', 'Web developer (JavaScript)', 'strong junior', '2015-10-30', 0, 0, 120, 6500, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course9Image.png', 6),
	(3, 'courseJava', 'ua', 'Програміст (Java)', 'Программист (Java)', 'Programmer  (Java)', 'strong junior', '2015-10-30', 0, 0, 30, 6700, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course3Image.png', 6),
	(4, 'C#', 'ua', 'Програміст (C#)', 'Программист (C#)', 'Programmer(C#)', 'strong junior', '2015-10-30', 0, 0, 40, 6000, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course4Image.png', 6),
	(5, 'C++', 'ua', 'Програміст (С++)', 'Программист (C++)', 'Programmer (С++)', 'intern', '2015-12-30', 0, 0, 36, 5900, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course2Image.png', 6),
	(6, 'ObjectiveC', 'ua', 'Програміст (Objective С)', 'Программист (Objective С)', 'Programmer(Objective С)', 'middle', '2015-10-30', 0, 0, 130, 7100, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course8Image.png', 4),
	(7, 'QA', 'ua', 'Тестувальник (QA)', 'Тестировщик (QA)', 'Quality assurance engineer(QA)', 'senior', '2016-02-28', 0, 0, 64, 6100, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course7Image.png', 6),
	(13, 'english', 'ua', 'Англійська мова для ІТ', 'Английский язык для ИТ', 'English for IT', 'middle', '2015-12-30', 0, 3, 60, 2500, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', 'Ви навчитеся писати чистий код;Користуватися системами контролю версій;Дізнаєтеся, з чого складається сучасний додаток;Для чого потрібен безперервна інтеграція (СІ) сервер;Чому потрібно тестувати свої програми і як це робити', 'Відеозаписи та текстові матеріали всіх онлайн-занять;Спілкування з розумними одногрупниками;Сертифікат про закінчення навчання;Прилаштованість на робоче місце в силіконовій долині', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course1Image.png', 6),
	(14, 'career', 'ua', 'Побудова успішної ІТ кар’єри', 'Построение успешной ИТ-карьеры', 'How to build a  successful career in IT', 'senior', '2015-12-30', 0, 3, 0, 0, 'хто відповідає за постановку завдань на розробку;для дизайнерів, які готові почати не просто малювати красиві картинки, а й навчитися тому, як створювати працюючі і зручні інтерфейси;для розробників, які хочуть самостійно створити або змінити свій проект\r\n [...]', '', '', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course3Image.png', 1),
	(18, 'verstka', 'ua', 'Верстальник сайтів (HTML, CSS)', 'Верстальщик сайтов (HTML, CSS)', 'Website layout specialist (HTML, CSS)', 'middle', '2015-12-30', 0, 0, 0, 5200, '', '', '', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course1Image.png', NULL),
	(19, 'coursePhpRu', 'ru', 'Інтернет програміст (РНР)', 'Интернет программист (РНР)', 'Web developer(PHP)', 'strong junior', '2015-07-30', 0, 14, 0, 6200, '', '', '', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course1Image.png', NULL),
	(20, 'englishRu', 'ru', 'Англійська мова для ІТ', 'Английский язык для ИТ', 'English for IT', 'middle', '2015-12-30', 0, 3, 0, 5600, '', '', '', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course1Image.png', NULL),
	(21, 'careerRu', 'ru', 'Побудова успішної ІТ кар’єри', 'Как построить успешную ІТ карьеру', 'How to build a  successful career in IT', 'senior', '2015-12-30', 0, 3, 0, 4500, '', '', '', NULL, NULL, NULL, 'who is responsible for setting objectives for development, for designers who are ready to start not just draw pretty pictures, but also learn how to create working and convenient interface, for developers who want to create their own or modify your project', NULL, NULL, 'course1Image.png', NULL),
	(22, '', 'ua', 'FrontEnd розробник (HTML/CSS, JavaScript)', 'FrontEnd разработчик (HTML/CSS, JavaScript)', 'FrontEnd developer (HTML/CSS, JavaScript)', 'strong junior', '2015-09-01', 0, 7, 0, 0, '', '', '', '', '', '', '', '', '', 'course1Image.png', NULL);
/*!40000 ALTER TABLE `course` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
