<?php

class m160713_190051_create_new_address_country extends CDbMigration
{
	public function safeUp()
	{
		$this->dropForeignKey('FK__address_country', 'address_city');
		$this->dropForeignKey('FK_user_address_country', 'user');
		$this->dropForeignKey('FK_user_address_city', 'user');
		$this->dropForeignKey('FK_acc_corporate_entity_address_city', 'acc_corporate_entity');
		$this->dropForeignKey('FK_acc_corporate_entity_address_city_2', 'acc_corporate_entity');
		$this->dropTable('address_country');
		$this->dropTable('address_city');

		$sql="CREATE TABLE `address_country`( id INT(3) NOT NULL AUTO_INCREMENT,title_ua VARCHAR(64) NOT NULL, title_ru VARCHAR(64) NOT NULL,title_en VARCHAR(64) NOT NULL,geocode VARCHAR(2) NOT NULL,  PRIMARY KEY (id) );
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Україна','Украина','Ukraine','UA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Білорусь','Беларусь','Belarus','BY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Молдова','Молдова','Moldova','MD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Польща','Польша','Poland','PL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Румунія','Румыния','Romania','RO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острів Вознесіння','о-в Вознесения','Ascension Island','AC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Андорра','Андорра','Andorra','AD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Обʼєднані Арабські Емірати','ОАЭ','United Arab Emirates','AE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Афганістан','Афганистан','Afghanistan','AF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Антигуа і Барбуда','Антигуа и Барбуда','Antigua & Barbuda','AG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ангілья','Ангилья','Anguilla','AI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Албанія','Албания','Albania','AL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Вірменія','Армения','Armenia','AM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ангола','Ангола','Angola','AO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Антарктика','Антарктида','Antarctica','AQ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Аргентина','Аргентина','Argentina','AR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Американське Самоа','Американское Самоа','American Samoa','AS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Австрія','Австрия','Austria','AT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Австралія','Австралия','Australia','AU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Аруба','Аруба','Aruba','AW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Аландські острови','Аландские о-ва','Åland Islands','AX');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Азербайджан','Азербайджан','Azerbaijan','AZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Боснія і Герцоговина','Босния и Герцеговина','Bosnia & Herzegovina','BA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Барбадос','Барбадос','Barbados','BB');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бангладеш','Бангладеш','Bangladesh','BD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бельгія','Бельгия','Belgium','BE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Буркіна-Фасо','Буркина-Фасо','Burkina Faso','BF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Болгарія','Болгария','Bulgaria','BG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бахрейн','Бахрейн','Bahrain','BH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бурунді','Бурунди','Burundi','BI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бенін','Бенин','Benin','BJ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сен-Бартельмі','Сен-Бартельми','St. Barthélemy','BL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бермуди','Бермудские о-ва','Bermuda','BM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бруней','Бруней-Даруссалам','Brunei','BN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Болівія','Боливия','Bolivia','BO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нідерландські Карибські острови','Бонэйр, Синт-Эстатиус и Саба','Caribbean Netherlands','BQ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бразилія','Бразилия','Brazil','BR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Багами','Багамские о-ва','Bahamas','BS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Бутан','Бутан','Bhutan','BT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ботсвана','Ботсвана','Botswana','BW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Беліз','Белиз','Belize','BZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Канада','Канада','Canada','CA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кокосові (Кілінгові) острови','Кокосовые о-ва','Cocos (Keeling) Islands','CC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Конго – Кіншаса','Конго - Киншаса','Congo - Kinshasa','CD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Центральноафриканська Республіка','ЦАР','Central African Republic','CF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Конго – Браззавіль','Конго - Браззавиль','Congo - Brazzaville','CG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Швейцарія','Швейцария','Switzerland','CH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кот-д’Івуар','Кот-д’Ивуар','Côte d’Ivoire','CI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острови Кука','о-ва Кука','Cook Islands','CK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Чилі','Чили','Chile','CL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Камерун','Камерун','Cameroon','CM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Китай','Китай','China','CN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Колумбія','Колумбия','Colombia','CO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Коста-Рика','Коста-Рика','Costa Rica','CR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Куба','Куба','Cuba','CU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кабо Верде','Кабо-Верде','Cape Verde','CV');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кюрасао','Кюрасао','Curaçao','CW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острів Різдва','о-в Рождества','Christmas Island','CX');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кіпр','Кипр','Cyprus','CY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Чехія','Чехия','Czech Republic','CZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Німеччина','Германия','Germany','DE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Дієго-Гарсія','Диего-Гарсия','Diego Garcia','DG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Джибуті','Джибути','Djibouti','DJ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Данія','Дания','Denmark','DK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Домініка','Доминика','Dominica','DM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Домініканська Республіка','Доминиканская Республика','Dominican Republic','DO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Алжир','Алжир','Algeria','DZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сеута і Мелілья','Сеута и Мелилья','Ceuta & Melilla','EA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Еквадор','Эквадор','Ecuador','EC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Естонія','Эстония','Estonia','EE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Єгипет','Египет','Egypt','EG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Західна Сахара','Западная Сахара','Western Sahara','EH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Еритрея','Эритрея','Eritrea','ER');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Іспанія','Испания','Spain','ES');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ефіопія','Эфиопия','Ethiopia','ET');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Фінляндія','Финляндия','Finland','FI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Фіджі','Фиджи','Fiji','FJ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Фолклендські острови','Фолклендские о-ва','Falkland Islands','FK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мікронезія','Федеративные Штаты Микронезии','Micronesia','FM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Фарерські острови','Фарерские о-ва','Faroe Islands','FO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Франція','Франция','France','FR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Габон','Габон','Gabon','GA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Велика Британія','Великобритания','United Kingdom','GB');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гренада','Гренада','Grenada','GD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Грузія','Грузия','Georgia','GE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Французька Гвіана','Французская Гвиана','French Guiana','GF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гернсі','Гернси','Guernsey','GG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гана','Гана','Ghana','GH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гібралтар','Гибралтар','Gibraltar','GI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гренландія','Гренландия','Greenland','GL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гамбія','Гамбия','Gambia','GM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гвінея','Гвинея','Guinea','GN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гваделупа','Гваделупа','Guadeloupe','GP');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Екваторіальна Гвінея','Экваториальная Гвинея','Equatorial Guinea','GQ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Греція','Греция','Greece','GR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Південна Джорджія та Південні Сандвічеві острови','Южная Георгия и Южные Сандвичевы о-ва','South Georgia & South Sandwich Islands','GS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гватемала','Гватемала','Guatemala','GT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гуам','Гуам','Guam','GU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гвінея-Бісау','Гвинея-Бисау','Guinea-Bissau','GW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гаяна','Гайана','Guyana','GY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гонконг, О.А.Р. Китаю','Гонконг (особый район)','Hong Kong SAR China','HK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гондурас','Гондурас','Honduras','HN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Хорватія','Хорватия','Croatia','HR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Гаїті','Гаити','Haiti','HT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Угорщина','Венгрия','Hungary','HU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Канарські острови','Канарские о-ва','Canary Islands','IC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Індонезія','Индонезия','Indonesia','ID');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ірландія','Ирландия','Ireland','IE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ізраїль','Израиль','Israel','IL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острів Мен','О-в Мэн','Isle of Man','IM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Індія','Индия','India','IN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Британські території в Індійському океані','Британская территория в Индийском океане','British Indian Ocean Territory','IO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ірак','Ирак','Iraq','IQ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Іран','Иран','Iran','IR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ісландія','Исландия','Iceland','IS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Італія','Италия','Italy','IT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Джерсі','Джерси','Jersey','JE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ямайка','Ямайка','Jamaica','JM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Йорданія','Иордания','Jordan','JO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Японія','Япония','Japan','JP');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кенія','Кения','Kenya','KE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Киргизстан','Киргизия','Kyrgyzstan','KG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Камбоджа','Камбоджа','Cambodia','KH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кірибаті','Кирибати','Kiribati','KI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Коморські острови','Коморские о-ва','Comoros','KM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сент-Кітс і Невіс','Сент-Китс и Невис','St. Kitts & Nevis','KN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Північна Корея','КНДР','North Korea','KP');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Південна Корея','Республика Корея','South Korea','KR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кувейт','Кувейт','Kuwait','KW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Кайманові острови','Каймановы о-ва','Cayman Islands','KY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Казахстан','Казахстан','Kazakhstan','KZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Лаос','Лаос','Laos','LA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ліван','Ливан','Lebanon','LB');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сент-Люсія','Сент-Люсия','St. Lucia','LC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ліхтенштейн','Лихтенштейн','Liechtenstein','LI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Шрі-Ланка','Шри-Ланка','Sri Lanka','LK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ліберія','Либерия','Liberia','LR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Лесото','Лесото','Lesotho','LS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Литва','Литва','Lithuania','LT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Люксембург','Люксембург','Luxembourg','LU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Латвія','Латвия','Latvia','LV');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Лівія','Ливия','Libya','LY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Марокко','Марокко','Morocco','MA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Монако','Монако','Monaco','MC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Чорногорія','Черногория','Montenegro','ME');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сен-Мартен','Сен-Мартен','St. Martin','MF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мадагаскар','Мадагаскар','Madagascar','MG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Маршаллові Острови','Маршалловы о-ва','Marshall Islands','MH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Македонія','Македония','Macedonia','MK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Малі','Мали','Mali','ML');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мʼянма (Бірма)','Мьянма (Бирма)','Myanmar (Burma)','MM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Монголія','Монголия','Mongolia','MN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Макао О.А.Р. Китаю','Макао (особый район)','Macau SAR China','MO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Північні Маріанські острови','Северные Марианские о-ва','Northern Mariana Islands','MP');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мартиніка','Мартиника','Martinique','MQ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мавританія','Мавритания','Mauritania','MR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Монтсеррат','Монтсеррат','Montserrat','MS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мальта','Мальта','Malta','MT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Маврикій','Маврикий','Mauritius','MU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мальдіви','Мальдивские о-ва','Maldives','MV');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Малаві','Малави','Malawi','MW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мексика','Мексика','Mexico','MX');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Малайзія','Малайзия','Malaysia','MY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Мозамбік','Мозамбик','Mozambique','MZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Намібія','Намибия','Namibia','NA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нова Каледонія','Новая Каледония','New Caledonia','NC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нігер','Нигер','Niger','NE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острів Норфолк','о-в Норфолк','Norfolk Island','NF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нігерія','Нигерия','Nigeria','NG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нікарагуа','Никарагуа','Nicaragua','NI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нідерланди','Нидерланды','Netherlands','NL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Норвегія','Норвегия','Norway','NO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Непал','Непал','Nepal','NP');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Науру','Науру','Nauru','NR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ніуе','Ниуэ','Niue','NU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Нова Зеландія','Новая Зеландия','New Zealand','NZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Оман','Оман','Oman','OM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Панама','Панама','Panama','PA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Перу','Перу','Peru','PE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Французька Полінезія','Французская Полинезия','French Polynesia','PF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Папуа Нова Гвінея','Папуа – Новая Гвинея','Papua New Guinea','PG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Філіппіни','Филиппины','Philippines','PH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Пакистан','Пакистан','Pakistan','PK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сен-Пʼєр і Мікелон','Сен-Пьер и Микелон','St. Pierre & Miquelon','PM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острови Піткерн','Питкэрн','Pitcairn Islands','PN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Пуерто-Рико','Пуэрто-Рико','Puerto Rico','PR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Палестинські території','Палестинские территории','Palestinian Territories','PS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Португалія','Португалия','Portugal','PT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Палау','Палау','Palau','PW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Парагвай','Парагвай','Paraguay','PY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Катар','Катар','Qatar','QA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Реюньйон','Реюньон','Réunion','RE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Румунія','Румыния','Romania','RO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сербія','Сербия','Serbia','RS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Росія','Россия','Russia','RU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Руанда','Руанда','Rwanda','RW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Саудівська Аравія','Саудовская Аравия','Saudi Arabia','SA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Соломонові Острови','Соломоновы о-ва','Solomon Islands','SB');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сейшельські острови','Сейшельские о-ва','Seychelles','SC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Судан','Судан','Sudan','SD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Швеція','Швеция','Sweden','SE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сінгапур','Сингапур','Singapore','SG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острів Святої Єлени','О-в Св. Елены','St. Helena','SH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Словенія','Словения','Slovenia','SI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острови Свальбард і Ян-Маєн','Шпицберген и Ян-Майен','Svalbard & Jan Mayen','SJ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Словаччина','Словакия','Slovakia','SK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сьєрра-Леоне','Сьерра-Леоне','Sierra Leone','SL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сан-Марино','Сан-Марино','San Marino','SM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сенегал','Сенегал','Senegal','SN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сомалі','Сомали','Somalia','SO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Суринам','Суринам','Suriname','SR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Південний Судан','Южный Судан','South Sudan','SS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сан-Томе і Прінсіпі','Сан-Томе и Принсипи','São Tomé & Príncipe','ST');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сальвадор','Сальвадор','El Salvador','SV');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сінт-Мартен','Синт-Мартен','Sint Maarten','SX');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сирія','Сирия','Syria','SY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Свазіленд','Свазиленд','Swaziland','SZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Трістан-да-Кунья','Тристан-да-Кунья','Tristan da Cunha','TA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Острови Теркс і Кайкос','О-ва Тёркс и Кайкос','Turks & Caicos Islands','TC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Чад','Чад','Chad','TD');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Французькі Південні Території','Французские Южные Территории','French Southern Territories','TF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Того','Того','Togo','TG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Таїланд','Таиланд','Thailand','TH');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Таджикистан','Таджикистан','Tajikistan','TJ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Токелау','Токелау','Tokelau','TK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Східний Тимор','Восточный Тимор','Timor-Leste','TL');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Туркменістан','Туркменистан','Turkmenistan','TM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Туніс','Тунис','Tunisia','TN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Тонга','Тонга','Tonga','TO');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Туреччина','Турция','Turkey','TR');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Тринідад і Тобаго','Тринидад и Тобаго','Trinidad & Tobago','TT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Тувалу','Тувалу','Tuvalu','TV');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Тайвань','Тайвань','Taiwan','TW');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Танзанія','Танзания','Tanzania','TZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Уганда','Уганда','Uganda','UG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Віддалені острови США','Внешние малые о-ва (США)','U.S. Outlying Islands','UM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('США','Соединенные Штаты','United States','US');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Уругвай','Уругвай','Uruguay','UY');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Узбекистан','Узбекистан','Uzbekistan','UZ');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ватикан','Ватикан','Vatican City','VA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Сент-Вінсент і Гренадини','Сент-Винсент и Гренадины','St. Vincent & Grenadines','VC');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Венесуела','Венесуэла','Venezuela','VE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Британські Віргінські острови','Виргинские о-ва (Британские)','British Virgin Islands','VG');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Віргінські острови, США','Виргинские о-ва (США)','U.S. Virgin Islands','VI');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Вʼєтнам','Вьетнам','Vietnam','VN');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Вануату','Вануату','Vanuatu','VU');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Волліс і Футуна','Уоллис и Футуна','Wallis & Futuna','WF');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Самоа','Самоа','Samoa','WS');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Косово','Косово','Kosovo','XK');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Ємен','Йемен','Yemen','YE');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Майотта','Майотта','Mayotte','YT');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('ПАР','ЮАР','South Africa','ZA');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Замбія','Замбия','Zambia','ZM');
		INSERT INTO `address_country` (`title_ua`, `title_ru`, `title_en`, `geocode`) VALUES ('Зімбабве','Зимбабве','Zimbabwe','ZW');";
		Yii::app()->db->createCommand($sql)->execute();


		$sql2="CREATE TABLE `address_city`( id INT(10) NOT NULL AUTO_INCREMENT,country INT(3),title_ua VARCHAR(64), title_ru VARCHAR(64),title_en VARCHAR(64), PRIMARY KEY (id) );
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Вінниця‎','Винница','Vinnytsia');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Дніпро','Днепр','Dnipro');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Донецьк‎','Донецк','Donetsk');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Житомир','Житомир','Zhytomyr');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Запоріжжя','Запорожье','Zaporizhzhia');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Івано-Франківськ','Ивано-Франковск','Ivano-Frankivsk');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Київ','Киев','Kyiv');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Кіровоград','Кировоград','Kirovohrad');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Луганськ','Луганск','Luhansk');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Луцьк','Луцк','Lutsk');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Львів','Львов','Lviv');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Миколаїв','Николаев','Mykolaiv');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Одеса','Одесса','Odesa');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Полтава','Полтава','Poltava');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Рівне','Ровно','Rivne');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Севастополь','Севастополь','Sevastopol');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Сімферополь','Симферополь','Simferopol');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Суми','Сумы','Sumy');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Тернопіль','Тернополь','Ternopil');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Ужгород','Ужгород','Uzhhorod');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Харків','Харьков','Kharkiv');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Херсон','Херсон','Kherson');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Хмельницький','Хмельницкий','Khmelnytskyi');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Черкаси','Черкассы','	Cherkasy');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Чернівці','Чернигов','Chernihiv');
		INSERT INTO `address_city` (`country`,`title_ua`, `title_ru`, `title_en`) VALUES ('1','Чернігів','Черновцы','Chernivtsi');";
		Yii::app()->db->createCommand($sql2)->execute();

		$this->update('user', array('country' => 1), 'country IS NOT NULL');
		$this->update('user', array('city' => 1), 'city IS NOT NULL');

		$this->update('acc_corporate_entity', array('legal_address_city_code' => 1));
		$this->update('acc_corporate_entity', array('actual_address_city_code' => 1));

		$this->addForeignKey('FK__address_country', 'address_city', 'country', 'address_country', 'id');
		$this->addForeignKey('FK_user_address_country', 'user', 'country', 'address_country', 'id');
		$this->addForeignKey('FK_user_address_city', 'user', 'city', 'address_city', 'id');

		$this->addForeignKey('FK_acc_corporate_entity_address_city', 'acc_corporate_entity', 'legal_address_city_code', 'address_city', 'id');
		$this->addForeignKey('FK_acc_corporate_entity_address_city_2', 'acc_corporate_entity', 'actual_address_city_code', 'address_city', 'id');
	}

	public function down()
	{
		$this->dropForeignKey('FK__address_country', 'address_city');
		$this->dropForeignKey('FK_user_address_country', 'user');
		$this->dropForeignKey('FK_user_address_city', 'user');
		$this->dropForeignKey('FK_acc_corporate_entity_address_city', 'acc_corporate_entity');
		$this->dropForeignKey('FK_acc_corporate_entity_address_city_2', 'acc_corporate_entity');
		$this->dropTable('address_country');
		$this->dropTable('address_city');
	}
}